### ISSUE TITLE
Document self hosted GitLab

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/terminus-build-tools-plugin#274]
The hostname can be set in `~/.terminus/config.yml`. For example:

```yml
build-tools:
  provider:
    git:
      gitlab:
        url: hostname
```

We should update `README.md`
