### ISSUE TITLE
Will we continue to maintain aliases?

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/terminus-build-tools-plugin#68]
The README for this repo means aliases like 

| Starter Site | Shorthand | Packagist Project Name                    |
| ------------ | --------- | ----------------------------------------- |
| Drupal 8     | d8        | [pantheon-systems/example-drops-8-composer](https://github.com/pantheon-systems/example-drops-8-composer) |
| Drupal 7     | d7        | [pantheon-systems/example-drops-7-composer](https://github.com/pantheon-systems/example-drops-7-composer) |

The 1.x branch contains logic for this aliases. I don't see the equivalent logic in the master branch. @greg-1-anderson, is this a feature you want to retain?

**Comment by greg-1-anderson** [comment]
Did that feature get left behind?

I was somewhat undecided about how to manage aliases, but I figure that at a minimum, we should support a few of the common ones.

**Comment by greg-1-anderson** [comment]
This is still supported on the master branch in [BuildToolsBase:: expandSourceAliases()](https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/9f4884b9bad88aae3ae4aa75aa2f624069c2eb5a/src/Commands/BuildToolsBase.php#L256)

**Comment by greg-1-anderson** [comment]
User-supplied shortcuts can be easily provided by the Terminus configuration feature. The user configuration file for Terminus is located at `~/.terminus/config.yml`.

There are two ways we could provide shortcuts.

1. List them with the default options for `build:project:create`:
```
command:
  build:
    project:
      create:
        options:
          admin-password: manticore
          team: Pantheon Open Source Team
        shortcuts:
          contenta: pantheon-systems/example-drops-8-composer:dev-contenta
          lightning: pantheon-systems/example-drops-8-composer:dev-lightning
```
2. Make `shortcuts` its own top-level component:
```
shortcuts:
  contenta: pantheon-systems/example-drops-8-composer:dev-contenta
  lightning: pantheon-systems/example-drops-8-composer:dev-lightning
command:
  build:
    project:
      create:
        options:
          admin-password: manticore
          team: Pantheon Open Source Team
```
Any preferences? **1** sort of makes sense from an organizational point of view (put the shortcuts with the command that uses them), but **2** might be more convenient for users, as they could then just put their shortcuts at the top of their configuration file.
